#!usr/bin/python
import os
import sys
import shutil

def placeData(merged_raster_dir, hillshade_app_dir):

    if merged_raster_dir[-1] is not '/':
        merged_raster_dir += '/'

    if hillshade_app_dir[-1] is not '/':
        hillshade_app_dir += '/'

    origin_path = merged_raster_dir + 'colorado.tif'
    destination_path = hillshade_app_dir + dem/gen/state/colorado/colorado/colorado.tif
    try:
        shutil.copy(origin_path, destination_path)
    except:
        print("Please pass the right directories in, or copy colorado.tif generated by merge.py into hillshade-app/dem/gen/state/colorado/colorado/")


if __name__ == '__main__':
    merge_rasters(sys.argv[1], sys.argv[2])
